apiVersion: v1
kind: Service
metadata:
  name: mdb
spec:
  selector:
    app: mdb
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdb
  labels:
    app: mdb
spec:
  selector:
    matchLabels:
      app: mdb
  replicas: 1 #кол-во подов
  template: #описание pod который будет создан
    metadata:
      labels:
        app: mdb
    spec:
     containers:
      - name: mdb
        image: mdb_image
        imagePullPolicy: Never
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: pers-top-secret
            mountPath: var/lib/mysql
     volumes:
      - name: pers-top-secret
        persistentVolumeClaim:
          claimName: top-secret
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mdb-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data_maridb"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mdb
  name: top-secret
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi