apiVersion: v1
kind: Service
metadata:
  name: mdb
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  selector:
    app: mdb
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      name: mdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mdb
  labels:
    app: mdb
spec:
  selector:
    matchLabels:
      app: mdb
  replicas: 1 #кол-во подов
  template: #описание pod который будет создан
    metadata:
      labels:
        app: mdb
    spec:
     containers:
      - name: mdb
        image: mdb_image
        imagePullPolicy: Never
        ports:
          - containerPort: 3306