apiVersion: v1
kind: Service
metadata:
  name: lb-nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  selector:
    app: nginx
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
    - protocol: TCP
      port : 443
      targetPort : 443
      name: https
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 1 #кол-во подов
  template: #описание pod который будет создан
    metadata:
      labels:
        app: nginx
    spec:
     containers:
      - name: nginx
        image: nginx_image
        imagePullPolicy: Never
        ports:
          - containerPort: 80
          - containerPort: 443