apiVersion: v1
kind: Service
metadata:
  name: php-nginx
  annotations:
    metallb.universe.tf/allow-shared-ip: wp
spec:
  selector:
    app: php
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050
      name: php
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
  replicas: 1 #кол-во подов
  template: #описание pod который будет создан
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: php_image
          imagePullPolicy: Never
          ports:
            - containerPort: 5050