apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  replicas: 1
  template:
    metadata:
      name: ftps-pod
      labels:
        app: ftps
    spec:
      containers:
        - name: ftps
          image: ftps_image
          imagePullPolicy: Never
          ports:
            - containerPort: 20
            - containerPort: 21
            - containerPort: 33333
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftps-folder
  labels:
    app: ftps
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
      apiVersion: v1
      kind: Service
      metadata:
        name: ftps
        labels:
          app: ftps
        annotations:
          metallb.universe.tf/allow-shared-ip: wp
      spec:
        externalTrafficPolicy: Cluster
        selector:
          app: ftps
        type: LoadBalancer
        loadBalancerIP: 192.168.99.101
        ports:
          - port: 20
            name: ftp-data
            targetPort: 20
          - port: 21
            name: ftp-command
            targetPort: 21
          - port: 33333
            name: ftp-psv
            targetPort: 33333
